services:
  db:
    image: uche21/mi_cine:v1
    container_name: contenedorMiCine
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: contrasenyaRoot
    ports:
      - "3306:3306"
    volumes:
      - datos_mysql:/var/lib/mysql  # <--- IMPORTANTE: Para no perder tus datos
    networks:
      - mi-red

  app:
    image: uche21/mi_app_cine:v1
    container_name: contenedorMiApp
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - mi-red

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: contenedorPhpMyAdmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: contrasenyaRoot
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - mi-red

networks:
  mi-red:
    driver: bridge

volumes:
  datos_mysql: # DefiniciÃ³n del volumen para la persistencia